# Generated by Django 5.2.4 on 2025-07-28 10:25

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='material/')),
                ('catalog', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
                ('title', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=home.models.Title, upload_to='product/')),
                ('catalog', models.ForeignKey(blank=home.models.Title, on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
                ('title', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.title')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
